services:
  - type: web
    name: unite-backend
    env: node
    plan: free
    buildCommand: cd unite-backend && npm install && npm run build
    startCommand: cd unite-backend && npm start
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.18.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_SSL
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: unite-postgres
          property: connectionString
      - key: APP_KEYS
        sync: false
      - key: API_TOKEN_SALT
        sync: false
      - key: ADMIN_JWT_SECRET
        sync: false
      - key: TRANSFER_TOKEN_SALT
        sync: false

databases:
  - name: unite-postgres
    plan: free
